# Generated by Django 5.2.17 on 2026-10-05 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=10, verbose_name='estado')),
                ('es_refuerzo', models.BooleanField(default=False, help_text='Se asigna automáticamente a quien hace clic en una simulación.', verbose_name='es curso de refuerzo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('SIMULACION', 'Simulación')], default='MANUAL', max_length=10, verbose_name='origen')),
                ('completada_en', models.DateTimeField(blank=True, null=True, verbose_name='completada en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='capacitacion.curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'asignación',
                'verbose_name_plural': 'asignaciones',
                'ordering': ['fecha_limite', 'id'],
                'constraints': [models.UniqueConstraint(fields=('curso', 'usuario'), name='asignacion_unica')],
            },
        ),
    ]
