# Generated by Django 5.2.17 on 2026-10-05 17:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nota_minima', models.PositiveSmallIntegerField(default=70, help_text='Sobre 100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='nota mínima')),
                ('intentos_maximos', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='intentos máximos')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='capacitacion.curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'evaluación',
                'verbose_name_plural': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nota')),
                ('aprobado', models.BooleanField(default=False, verbose_name='aprobado')),
                ('respuestas', models.JSONField(default=dict, verbose_name='respuestas')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='capacitacion.evaluacion', verbose_name='evaluación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'intento',
                'verbose_name_plural': 'intentos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('contenido_html', models.TextField(blank=True, verbose_name='contenido')),
                ('video_url', models.URLField(blank=True, verbose_name='URL del video')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='capacitacion.curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'lección',
                'verbose_name_plural': 'lecciones',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('enunciado', models.TextField(verbose_name='enunciado')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='capacitacion.evaluacion', verbose_name='evaluación')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('texto', models.CharField(max_length=300, verbose_name='texto')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='es correcta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='capacitacion.pregunta', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'opción',
                'verbose_name_plural': 'opciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('completada_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='completada en')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='capacitacion.asignacion', verbose_name='asignación')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='capacitacion.leccion', verbose_name='lección')),
            ],
            options={
                'verbose_name': 'progreso de lección',
                'verbose_name_plural': 'progresos de lección',
                'constraints': [models.UniqueConstraint(fields=('asignacion', 'leccion'), name='progreso_unico')],
            },
        ),
    ]
