# Generated by Django 5.2.17 on 2026-10-05 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('accion', models.CharField(db_index=True, max_length=50, verbose_name='acción')),
                ('objeto', models.CharField(blank=True, max_length=200, verbose_name='objeto')),
                ('detalle', models.JSONField(blank=True, default=dict, verbose_name='detalle')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('ocurrido_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ocurrido en')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_bitacora', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de bitácora',
                'verbose_name_plural': 'bitácora',
                'ordering': ['-ocurrido_en'],
            },
        ),
    ]
