# Generated by Django 5.2.17 on 2026-10-05 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSospechoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('remitente', models.CharField(help_text='Correo o nombre que aparece como remitente.', max_length=254, verbose_name='remitente')),
                ('asunto', models.CharField(max_length=300, verbose_name='asunto')),
                ('fecha_recepcion', models.DateTimeField(verbose_name='fecha de recepción')),
                ('descripcion', models.TextField(blank=True, help_text='Opcional: qué le pareció sospechoso.', verbose_name='comentarios')),
                ('adjunto_url', models.CharField(blank=True, help_text='Ruta del archivo en Supabase Storage.', max_length=300, verbose_name='adjunto')),
                ('adjunto_nombre', models.CharField(blank=True, max_length=255, verbose_name='nombre del adjunto')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('PHISHING_CONFIRMADO', 'Phishing confirmado'), ('FALSO_POSITIVO', 'Falso positivo')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('comentario_admin', models.TextField(blank=True, verbose_name='comentario del Administrador')),
                ('atendido_en', models.DateTimeField(blank=True, null=True, verbose_name='atendido en')),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='atendido por')),
                ('destinatario_sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='simulaciones.destinatario', verbose_name='destinatario de simulación')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL, verbose_name='reportado por')),
            ],
            options={
                'verbose_name': 'reporte de correo sospechoso',
                'verbose_name_plural': 'reportes de correos sospechosos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
