-- PhishGuard: esquema de base de datos para PostgreSQL (Supabase).
-- Generado con 'python manage.py sqlmigrate' a partir de las migraciones de Django.
-- La forma recomendada de crear la base es 'python manage.py migrate'; este archivo es de referencia.

-- ===== usuarios 0001 =====
BEGIN;
--
-- Create model Departamento
--
CREATE TABLE "usuarios_departamento" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "nombre" varchar(120) NOT NULL UNIQUE, "activo" boolean NOT NULL);
--
-- Create model Usuario
--
CREATE TABLE "usuarios_usuario" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "nombre_completo" varchar(150) NOT NULL, "rol" varchar(12) NOT NULL, "intentos_fallidos" smallint NOT NULL CHECK ("intentos_fallidos" >= 0), "bloqueado_hasta" timestamp with time zone NULL, "departamento_id" bigint NULL);
CREATE TABLE "usuarios_usuario_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "usuarios_usuario_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE INDEX "usuarios_departamento_nombre_db4afb7f_like" ON "usuarios_departamento" ("nombre" varchar_pattern_ops);
ALTER TABLE "usuarios_usuario" ADD CONSTRAINT "usuarios_usuario_departamento_id_b6b46aa0_fk_usuarios_" FOREIGN KEY ("departamento_id") REFERENCES "usuarios_departamento" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "usuarios_usuario_email_0a82e5f9_like" ON "usuarios_usuario" ("email" varchar_pattern_ops);
CREATE INDEX "usuarios_usuario_departamento_id_b6b46aa0" ON "usuarios_usuario" ("departamento_id");
ALTER TABLE "usuarios_usuario_groups" ADD CONSTRAINT "usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq" UNIQUE ("usuario_id", "group_id");
ALTER TABLE "usuarios_usuario_groups" ADD CONSTRAINT "usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_" FOREIGN KEY ("usuario_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usuarios_usuario_groups" ADD CONSTRAINT "usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "usuarios_usuario_groups_usuario_id_7a34077f" ON "usuarios_usuario_groups" ("usuario_id");
CREATE INDEX "usuarios_usuario_groups_group_id_e77f6dcf" ON "usuarios_usuario_groups" ("group_id");
ALTER TABLE "usuarios_usuario_user_permissions" ADD CONSTRAINT "usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq" UNIQUE ("usuario_id", "permission_id");
ALTER TABLE "usuarios_usuario_user_permissions" ADD CONSTRAINT "usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_" FOREIGN KEY ("usuario_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usuarios_usuario_user_permissions" ADD CONSTRAINT "usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "usuarios_usuario_user_permissions_usuario_id_60aeea80" ON "usuarios_usuario_user_permissions" ("usuario_id");
CREATE INDEX "usuarios_usuario_user_permissions_permission_id_4e5c0f2f" ON "usuarios_usuario_user_permissions" ("permission_id");
COMMIT;

-- ===== panel 0001 =====
BEGIN;
--
-- Create model Bitacora
--
CREATE TABLE "panel_bitacora" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "accion" varchar(50) NOT NULL, "objeto" varchar(200) NOT NULL, "detalle" jsonb NOT NULL, "ip" inet NULL, "ocurrido_en" timestamp with time zone NOT NULL, "usuario_id" bigint NULL);
ALTER TABLE "panel_bitacora" ADD CONSTRAINT "panel_bitacora_usuario_id_cda0d35b_fk_usuarios_usuario_id" FOREIGN KEY ("usuario_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "panel_bitacora_accion_f7d71e5a" ON "panel_bitacora" ("accion");
CREATE INDEX "panel_bitacora_accion_f7d71e5a_like" ON "panel_bitacora" ("accion" varchar_pattern_ops);
CREATE INDEX "panel_bitacora_ocurrido_en_6c7c803e" ON "panel_bitacora" ("ocurrido_en");
CREATE INDEX "panel_bitacora_usuario_id_cda0d35b" ON "panel_bitacora" ("usuario_id");
COMMIT;

-- ===== capacitacion 0001 =====
BEGIN;
--
-- Create model Curso
--
CREATE TABLE "capacitacion_curso" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "titulo" varchar(200) NOT NULL, "descripcion" text NOT NULL, "estado" varchar(10) NOT NULL, "es_refuerzo" boolean NOT NULL, "creado_por_id" bigint NULL);
--
-- Create model Asignacion
--
CREATE TABLE "capacitacion_asignacion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "fecha_limite" date NULL, "origen" varchar(10) NOT NULL, "completada_en" timestamp with time zone NULL, "usuario_id" bigint NOT NULL, "curso_id" bigint NOT NULL, CONSTRAINT "asignacion_unica" UNIQUE ("curso_id", "usuario_id"));
ALTER TABLE "capacitacion_curso" ADD CONSTRAINT "capacitacion_curso_creado_por_id_e1710ef3_fk_usuarios_" FOREIGN KEY ("creado_por_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "capacitacion_curso_creado_por_id_e1710ef3" ON "capacitacion_curso" ("creado_por_id");
ALTER TABLE "capacitacion_asignacion" ADD CONSTRAINT "capacitacion_asignac_usuario_id_eac023c0_fk_usuarios_" FOREIGN KEY ("usuario_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "capacitacion_asignacion" ADD CONSTRAINT "capacitacion_asignac_curso_id_056f0de3_fk_capacitac" FOREIGN KEY ("curso_id") REFERENCES "capacitacion_curso" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "capacitacion_asignacion_usuario_id_eac023c0" ON "capacitacion_asignacion" ("usuario_id");
CREATE INDEX "capacitacion_asignacion_curso_id_056f0de3" ON "capacitacion_asignacion" ("curso_id");
COMMIT;

-- ===== capacitacion 0002 =====
BEGIN;
--
-- Create model Evaluacion
--
CREATE TABLE "capacitacion_evaluacion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "nota_minima" smallint NOT NULL CHECK ("nota_minima" >= 0), "intentos_maximos" smallint NOT NULL CHECK ("intentos_maximos" >= 0), "curso_id" bigint NOT NULL UNIQUE);
--
-- Create model Intento
--
CREATE TABLE "capacitacion_intento" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "nota" numeric(5, 2) NOT NULL, "aprobado" boolean NOT NULL, "respuestas" jsonb NOT NULL, "evaluacion_id" bigint NOT NULL, "usuario_id" bigint NOT NULL);
--
-- Create model Leccion
--
CREATE TABLE "capacitacion_leccion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "orden" smallint NOT NULL CHECK ("orden" >= 0), "titulo" varchar(200) NOT NULL, "contenido_html" text NOT NULL, "video_url" varchar(200) NOT NULL, "curso_id" bigint NOT NULL);
--
-- Create model Pregunta
--
CREATE TABLE "capacitacion_pregunta" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "enunciado" text NOT NULL, "orden" smallint NOT NULL CHECK ("orden" >= 0), "evaluacion_id" bigint NOT NULL);
--
-- Create model Opcion
--
CREATE TABLE "capacitacion_opcion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "texto" varchar(300) NOT NULL, "es_correcta" boolean NOT NULL, "pregunta_id" bigint NOT NULL);
--
-- Create model ProgresoLeccion
--
CREATE TABLE "capacitacion_progresoleccion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "completada_en" timestamp with time zone NOT NULL, "asignacion_id" bigint NOT NULL, "leccion_id" bigint NOT NULL, CONSTRAINT "progreso_unico" UNIQUE ("asignacion_id", "leccion_id"));
ALTER TABLE "capacitacion_evaluacion" ADD CONSTRAINT "capacitacion_evaluac_curso_id_4afbabb9_fk_capacitac" FOREIGN KEY ("curso_id") REFERENCES "capacitacion_curso" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "capacitacion_intento" ADD CONSTRAINT "capacitacion_intento_evaluacion_id_161e6710_fk_capacitac" FOREIGN KEY ("evaluacion_id") REFERENCES "capacitacion_evaluacion" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "capacitacion_intento" ADD CONSTRAINT "capacitacion_intento_usuario_id_97a38c9e_fk_usuarios_usuario_id" FOREIGN KEY ("usuario_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "capacitacion_intento_evaluacion_id_161e6710" ON "capacitacion_intento" ("evaluacion_id");
CREATE INDEX "capacitacion_intento_usuario_id_97a38c9e" ON "capacitacion_intento" ("usuario_id");
ALTER TABLE "capacitacion_leccion" ADD CONSTRAINT "capacitacion_leccion_curso_id_44f49cfa_fk_capacitacion_curso_id" FOREIGN KEY ("curso_id") REFERENCES "capacitacion_curso" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "capacitacion_leccion_curso_id_44f49cfa" ON "capacitacion_leccion" ("curso_id");
ALTER TABLE "capacitacion_pregunta" ADD CONSTRAINT "capacitacion_pregunt_evaluacion_id_e634d53d_fk_capacitac" FOREIGN KEY ("evaluacion_id") REFERENCES "capacitacion_evaluacion" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "capacitacion_pregunta_evaluacion_id_e634d53d" ON "capacitacion_pregunta" ("evaluacion_id");
ALTER TABLE "capacitacion_opcion" ADD CONSTRAINT "capacitacion_opcion_pregunta_id_a4bcbba4_fk_capacitac" FOREIGN KEY ("pregunta_id") REFERENCES "capacitacion_pregunta" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "capacitacion_opcion_pregunta_id_a4bcbba4" ON "capacitacion_opcion" ("pregunta_id");
ALTER TABLE "capacitacion_progresoleccion" ADD CONSTRAINT "capacitacion_progres_asignacion_id_bbfb4014_fk_capacitac" FOREIGN KEY ("asignacion_id") REFERENCES "capacitacion_asignacion" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "capacitacion_progresoleccion" ADD CONSTRAINT "capacitacion_progres_leccion_id_1231d899_fk_capacitac" FOREIGN KEY ("leccion_id") REFERENCES "capacitacion_leccion" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "capacitacion_progresoleccion_asignacion_id_bbfb4014" ON "capacitacion_progresoleccion" ("asignacion_id");
CREATE INDEX "capacitacion_progresoleccion_leccion_id_1231d899" ON "capacitacion_progresoleccion" ("leccion_id");
COMMIT;

-- ===== simulaciones 0001 =====
BEGIN;
--
-- Create model PlantillaCorreo
--
CREATE TABLE "simulaciones_plantillacorreo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "nombre" varchar(150) NOT NULL, "asunto" varchar(200) NOT NULL, "remitente_visible" varchar(200) NOT NULL, "cuerpo_html" text NOT NULL, "dificultad" varchar(5) NOT NULL, "tiene_formulario" boolean NOT NULL, "senales" text NOT NULL);
--
-- Create model Campana
--
CREATE TABLE "simulaciones_campana" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "nombre" varchar(150) NOT NULL, "fecha_envio" timestamp with time zone NOT NULL, "estado" varchar(10) NOT NULL, "creado_por_id" bigint NULL, "curso_refuerzo_id" bigint NULL, "plantilla_id" bigint NOT NULL);
CREATE TABLE "simulaciones_campana_departamentos" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "campana_id" bigint NOT NULL, "departamento_id" bigint NOT NULL);
--
-- Create model Destinatario
--
CREATE TABLE "simulaciones_destinatario" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "token" uuid NOT NULL UNIQUE, "enviado_en" timestamp with time zone NULL, "campana_id" bigint NOT NULL, "usuario_id" bigint NOT NULL);
--
-- Create model EventoSimulacion
--
CREATE TABLE "simulaciones_eventosimulacion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "tipo" varchar(16) NOT NULL, "ocurrido_en" timestamp with time zone NOT NULL, "user_agent" varchar(300) NOT NULL, "destinatario_id" bigint NOT NULL);
--
-- Create constraint destinatario_unico on model destinatario
--
ALTER TABLE "simulaciones_destinatario" ADD CONSTRAINT "destinatario_unico" UNIQUE ("campana_id", "usuario_id");
--
-- Create index evento_dest_tipo_idx on field(s) destinatario, tipo of model eventosimulacion
--
CREATE INDEX "evento_dest_tipo_idx" ON "simulaciones_eventosimulacion" ("destinatario_id", "tipo");
ALTER TABLE "simulaciones_campana" ADD CONSTRAINT "simulaciones_campana_creado_por_id_8da935d2_fk_usuarios_" FOREIGN KEY ("creado_por_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "simulaciones_campana" ADD CONSTRAINT "simulaciones_campana_curso_refuerzo_id_b36050da_fk_capacitac" FOREIGN KEY ("curso_refuerzo_id") REFERENCES "capacitacion_curso" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "simulaciones_campana" ADD CONSTRAINT "simulaciones_campana_plantilla_id_f3ed1006_fk_simulacio" FOREIGN KEY ("plantilla_id") REFERENCES "simulaciones_plantillacorreo" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "simulaciones_campana_creado_por_id_8da935d2" ON "simulaciones_campana" ("creado_por_id");
CREATE INDEX "simulaciones_campana_curso_refuerzo_id_b36050da" ON "simulaciones_campana" ("curso_refuerzo_id");
CREATE INDEX "simulaciones_campana_plantilla_id_f3ed1006" ON "simulaciones_campana" ("plantilla_id");
ALTER TABLE "simulaciones_campana_departamentos" ADD CONSTRAINT "simulaciones_campana_dep_campana_id_departamento__68d22814_uniq" UNIQUE ("campana_id", "departamento_id");
ALTER TABLE "simulaciones_campana_departamentos" ADD CONSTRAINT "simulaciones_campana_campana_id_d82e9fb9_fk_simulacio" FOREIGN KEY ("campana_id") REFERENCES "simulaciones_campana" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "simulaciones_campana_departamentos" ADD CONSTRAINT "simulaciones_campana_departamento_id_cceb6f15_fk_usuarios_" FOREIGN KEY ("departamento_id") REFERENCES "usuarios_departamento" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "simulaciones_campana_departamentos_campana_id_d82e9fb9" ON "simulaciones_campana_departamentos" ("campana_id");
CREATE INDEX "simulaciones_campana_departamentos_departamento_id_cceb6f15" ON "simulaciones_campana_departamentos" ("departamento_id");
ALTER TABLE "simulaciones_destinatario" ADD CONSTRAINT "simulaciones_destina_campana_id_82567ee4_fk_simulacio" FOREIGN KEY ("campana_id") REFERENCES "simulaciones_campana" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "simulaciones_destinatario" ADD CONSTRAINT "simulaciones_destina_usuario_id_4f28316e_fk_usuarios_" FOREIGN KEY ("usuario_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "simulaciones_destinatario_campana_id_82567ee4" ON "simulaciones_destinatario" ("campana_id");
CREATE INDEX "simulaciones_destinatario_usuario_id_4f28316e" ON "simulaciones_destinatario" ("usuario_id");
ALTER TABLE "simulaciones_eventosimulacion" ADD CONSTRAINT "simulaciones_eventos_destinatario_id_030a6550_fk_simulacio" FOREIGN KEY ("destinatario_id") REFERENCES "simulaciones_destinatario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "simulaciones_eventosimulacion_destinatario_id_030a6550" ON "simulaciones_eventosimulacion" ("destinatario_id");
COMMIT;

-- ===== reportes 0001 =====
BEGIN;
--
-- Create model ReporteSospechoso
--
CREATE TABLE "reportes_reportesospechoso" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "remitente" varchar(254) NOT NULL, "asunto" varchar(300) NOT NULL, "fecha_recepcion" timestamp with time zone NOT NULL, "descripcion" text NOT NULL, "adjunto_url" varchar(300) NOT NULL, "adjunto_nombre" varchar(255) NOT NULL, "estado" varchar(20) NOT NULL, "comentario_admin" text NOT NULL, "atendido_en" timestamp with time zone NULL, "atendido_por_id" bigint NULL, "destinatario_sim_id" bigint NULL, "reportado_por_id" bigint NOT NULL);
ALTER TABLE "reportes_reportesospechoso" ADD CONSTRAINT "reportes_reportesosp_atendido_por_id_298ee331_fk_usuarios_" FOREIGN KEY ("atendido_por_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reportes_reportesospechoso" ADD CONSTRAINT "reportes_reportesosp_destinatario_sim_id_434367d1_fk_simulacio" FOREIGN KEY ("destinatario_sim_id") REFERENCES "simulaciones_destinatario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reportes_reportesospechoso" ADD CONSTRAINT "reportes_reportesosp_reportado_por_id_465014b5_fk_usuarios_" FOREIGN KEY ("reportado_por_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reportes_reportesospechoso_estado_c3ecd375" ON "reportes_reportesospechoso" ("estado");
CREATE INDEX "reportes_reportesospechoso_estado_c3ecd375_like" ON "reportes_reportesospechoso" ("estado" varchar_pattern_ops);
CREATE INDEX "reportes_reportesospechoso_atendido_por_id_298ee331" ON "reportes_reportesospechoso" ("atendido_por_id");
CREATE INDEX "reportes_reportesospechoso_destinatario_sim_id_434367d1" ON "reportes_reportesospechoso" ("destinatario_sim_id");
CREATE INDEX "reportes_reportesospechoso_reportado_por_id_465014b5" ON "reportes_reportesospechoso" ("reportado_por_id");
COMMIT;

-- ===== Seguridad: RLS para que la API REST pública de Supabase no exponga datos =====
DO $$ DECLARE t record; BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;
END $$;
