# Generated by Django 5.2.17 on 2026-10-05 17:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitacion', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('asunto', models.CharField(max_length=200, verbose_name='asunto')),
                ('remitente_visible', models.CharField(help_text='Nombre y correo que verá el destinatario, p. ej. «Banco X <avisos@bx.com>».', max_length=200, verbose_name='remitente visible')),
                ('cuerpo_html', models.TextField(help_text='Use {{enlace}} donde debe ir el enlace de la simulación.', verbose_name='cuerpo HTML')),
                ('dificultad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=5, verbose_name='dificultad')),
                ('tiene_formulario', models.BooleanField(default=False, help_text='Al hacer clic se muestra un formulario falso antes de la página educativa.', verbose_name='tiene formulario')),
                ('senales', models.TextField(blank=True, help_text='Una señal por línea; se muestran en la página educativa (RF-20).', verbose_name='señales de alerta')),
            ],
            options={
                'verbose_name': 'plantilla de correo',
                'verbose_name_plural': 'plantillas de correo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de envío')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('ENVIANDO', 'Enviando'), ('FINALIZADA', 'Finalizada')], default='PROGRAMADA', max_length=10, verbose_name='estado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('curso_refuerzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='capacitacion.curso', verbose_name='curso de refuerzo')),
                ('departamentos', models.ManyToManyField(blank=True, to='usuarios.departamento', verbose_name='departamentos')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas', to='simulaciones.plantillacorreo', verbose_name='plantilla')),
            ],
            options={
                'verbose_name': 'campaña',
                'verbose_name_plural': 'campañas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='enviado en')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='simulaciones.campana', verbose_name='campaña')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos_simulacion', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'destinatario',
                'verbose_name_plural': 'destinatarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura'), ('CLIC', 'Clic'), ('ENVIO_FORMULARIO', 'Envío de formulario'), ('REPORTE', 'Reporte')], max_length=16, verbose_name='tipo')),
                ('ocurrido_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ocurrido en')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='user agent')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='simulaciones.destinatario', verbose_name='destinatario')),
            ],
            options={
                'verbose_name': 'evento de simulación',
                'verbose_name_plural': 'eventos de simulación',
                'ordering': ['-ocurrido_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='destinatario',
            constraint=models.UniqueConstraint(fields=('campana', 'usuario'), name='destinatario_unico'),
        ),
        migrations.AddIndex(
            model_name='eventosimulacion',
            index=models.Index(fields=['destinatario', 'tipo'], name='evento_dest_tipo_idx'),
        ),
    ]
